---
# Name of the keycloak stack, used for Docker container naming and the postgres storage path
keycloak_stack_name: keycloak
# The URL that is used for the base of all routes for Keycloak
keycloak_frontend_url: "http://localhost:8080/auth"
