dependencies:
  - docker
  - role: docker_swarm_network
    vars:
      docker_network_name: "{{traefik_docker_network}}"
      docker_network_driver: "overlay"
  - role: docker_stack_create
    vars:
      stack_name: "{{traefik_stack_name}}"
      service_imbude:
        network_bindpoints:
          "traefik":
            "acme-store":
              src: "/etc/traefik/acme/"
            "dynamic-traefik-config":
              src: "/etc/traefik/conf.d/"

        traefik:
          "traefik":
            "traefik-dash":
              enabled: TRUE
              route_rule: "{{traefik_external_rule}}"
              service_override: "api@internal"
              
      compose:
        version: "3.8"
        services:
          traefik:
            image: traefik
            command:
              - "--api.insecure=true"
              - "--api.dashboard=true"
              - "--entrypoints.http.address=:80"
              - "--entrypoints.https.address=:443"
              - "--providers.docker"
              - "--providers.docker.swarmmode=true"
              - "--providers.docker.network={{traefik_docker_network}}"
              - "--providers.file.directory=/etc/traefik/conf.d/"
              - "--providers.file.watch=true"
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            ports:
              - target: 80
                published: 80
              - target: 443
                published: 443
            deploy:
              mode: global
              placement:
                constraints:
                  - node.role == manager
              update_config:
                parallelism: 1
                delay: 10s
              restart_policy:
                condition: any
